<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contactos [
<!ELEMENT contactos (contacto*)>
<!ELEMENT contacto (nome, fixo?, mobil+,correo*)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT fixo (#PCDATA)>
<!ELEMENT mobil (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
]>

<contactos>
    <contacto>
        <nome>Xoel</nome>
        <fixo>9898989543</fixo>
        <mobil>6444323544</mobil>
    </contacto>
    <contacto>
        <nome>Noa</nome>
        <fixo>998899889</fixo>
        <mobil>644432344</mobil>
        <mobil>473824898</mobil>
        <correo>noa.vila@traballo.com</correo>
        <correo>noa@omeucorreo.com</correo>
    </contacto>
</contactos>