=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA6B/UD4_T6B_EloyRodalPerez.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tabla_periodica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="elemento" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="simbolo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]{0,2}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="numero_atomico" type="xs:integer" />
                            <xs:element name="punto_ebullicion">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="unidades" type="xs:string"
                                                default="centigrados" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="densidad">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="unidades" type="xs:string" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="estado" type="xs:string" />
                        <xs:attribute name="grupo" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="grupo" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="descripcion" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== EloRP/DAM1_LDM/UD4_A1/TAREFA6B/UD4_T6B_EloyRodalPérez.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabla_periodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UD4_T6B_EloyRodalPerez.xsd">
    <elemento estado="gas" grupo="1">
        <nombre>Litio</nombre>
        <simbolo>Li</simbolo>
        <numero_atomico>3</numero_atomico>
        <punto_ebullicion unidades="kelvin">1615</punto_ebullicion>
        <densidad unidades="gramos/centímetros cúbicos">0.534</densidad>
    </elemento>
    <elemento estado="sólido" grupo="1">
        <nombre>Sodio</nombre>
        <simbolo>Na</simbolo>
        <numero_atomico>11</numero_atomico>
        <punto_ebullicion unidades="kelvin">1156</punto_ebullicion>
        <densidad unidades="gramos/centímetros cúbicos">0.971</densidad>
    </elemento>
    <grupo numero="1">
        <nombre>Metales alcalinos</nombre>
        <descripcion>Son metales blandos, muy reactivos y tienen solo un electrón en la capa de
            valencia.</descripcion>
    </grupo>
    <grupo numero="18">
        <nombre>Gases nobles</nombre>
        <descripcion>Son gases incoloros, inodoros e insípidos y tienen una baja reactividad química.</descripcion>
    </grupo>
</tabla_periodica>
