=== EloRP/DAM1_LDM/UD3/UD3_A1/TAREFA8/UD3_T8_EloyRodalPerez.dtd
<!-- El DTD inicial (primera línea) nos da el elemento raíz del DTD y sus hijos:
Presentacion, una o más instancias de estudios o experienciaLaboral, cero o más instancias de los
siguientes tres elementos opcionales
idiomas, deportes y otros, el elemento opcional referencias, seguido de otro elemento opcional
observaciones.-->

<!ELEMENT curriculumVitae (presentacion, (estudios | experienciaLaboral)+, (idiomas | deportes | otros)*, referencias*, observaciones?)>
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT estudios (#PCDATA)>
<!ATTLIST estudios notamedia CDATA #IMPLIED>
<!ELEMENT empresaPracticas EMPTY>
<!ATTLIST empresaPracticas
    nombreEmpresa CDATA #REQUIRED
    horasRealizadas CDATA #REQUIRED>
<!ELEMENT experienciaLaboral (#PCDATA)>
<!ELEMENT idiomas EMPTY>
<!ATTLIST idiomas
    nombre CDATA "galego"
    nivel (bajo | medio | alto) "medio">
<!ELEMENT deportes (#PCDATA)>
<!ELEMENT otros (#PCDATA)>
<!ELEMENT referencias (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>

=== EloRP/DAM1_LDM/UD3/UD3_A1/TAREFA8/UD3_T8_EloyRodalPerez.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!-- DTD -->
<!DOCTYPE curriculumVitae SYSTEM "UD3_T8_EloyRodalPerez.dtd">

<!-- XML -->
<curriculumVitae>
    <presentacion>PRESENTACIÓN VA AQUÍ</presentacion>
    <estudios>PREESCOLAR</estudios>
    <estudios>PRIMARIA</estudios>
    <estudios>ESO</estudios>
    <estudios>BACHILLERATO</estudios>
    <estudios>FP SUPERIOR</estudios>
    <idiomas nombre="galego" nivel="alto" />
    <idiomas nombre="español" nivel="alto" />
    <idiomas nombre="inglés" nivel="alto" />
    <idiomas nombre="francés" nivel="bajo" />

    <otros>OTROS DATOS</otros>
    <referencias>REFERENCIAS AQUÍ</referencias>
    <observaciones>OBSERVACIOES AQUÍ</observaciones>
</curriculumVitae>
