<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!-- DTD -->
<!DOCTYPE mensaxe [
<!ELEMENT mensaxe (de, para+, asunto, corpo?, adxunto*)>
<!ATTLIST mensaxe prioridade (baixa | normal | urxente) "normal">
<!ATTLIST mensaxe gardarBandexa CDATA "Enviados">
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT corpo (#PCDATA)>
<!ELEMENT adxunto (#PCDATA)>
]>
<!-- XML -->
<mensaxe prioridade="urxente" gardarBandexa="">
    <de>eloyrodal.p@gmail.com</de>
    <para>corregenerico1@gmail.com</para>
    <para>correoestandar2@edu.xunta.es</para>
    <para>correo@hotmail.com</para>
    <asunto>Asunto do correo electr√≥nico</asunto>
    <corpo>Lorem ipsum dolor sit amet (...)</corpo>
    <adxunto>D:\arquivoadxunto.txt</adxunto>
    <adxunto>D:\docs\exame3trimestre.pdf</adxunto>
    <adxunto>D:\fotos\foto.png</adxunto>
</mensaxe>