=== EloRP/DAM1_LDM/UD3/UD3_A1/TAREFA7/UD3_T7b_EloyRodalPerez.dtd
<!ELEMENT informe (descripcion?, seguro+, fechaInforme)>
<!ELEMENT fechaInforme EMPTY>
<!ELEMENT seguro (numero, (cliente-Personal | cliente-Empresa))>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cliente-Personal (#PCDATA)>
<!ELEMENT cliente-Empresa (#PCDATA)>
<!ATTLIST seguro tipo (edificio | contenido) #REQUIRED>
<!ATTLIST fechaInforme
    fechaInicio CDATA #REQUIRED
    fechaFin CDATA #IMPLIED>

=== EloRP/DAM1_LDM/UD3/UD3_A1/TAREFA7/UD3_T7b_EloyRodalPerez.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!-- DTD -->
<!DOCTYPE informe SYSTEM "UD3_T7b_EloyRodalPerez.dtd">

<!--XML-->
<informe>
    <descripcion>DESCRIPCION</descripcion>
    <seguro tipo="edificio">
        <numero>12345</numero>
        <cliente-Personal>NOMBRECLIENTE</cliente-Personal>
    </seguro>
    <seguro tipo="contenido">
        <numero>12345</numero>
        <cliente-Empresa>NOMBRECLIENTEEMPRESA</cliente-Empresa>
    </seguro>
    <fechaInforme fechaInicio="X-0X-200X" />
</informe>
