=== EloRP/DAM1_LDM/UD4_A1/TAREFA4B/Pizza.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="pizza">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tamaño" type="xs:string" default="mediana" />
                <xs:element name="tipo" type="xs:string" default="base" />
                <!-- ingredientes adicionales -->
                <xs:element name="extra_mozzarela" type="xs:string" default="Yes" minOccurs="0" />
                <xs:element name="anchoas" type="xs:string" default="Yes" minOccurs="0" />
                <xs:element name="atún" type="xs:string" default="Yes" minOccurs="0" />
                <xs:element name="pimiento" type="xs:string" default="Yes" minOccurs="0" />
                <xs:element name="jamón" type="xs:string" default="Yes" minOccurs="0" />
                <!-- datos de la entrega -->
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="apellidos" type="xs:string" />
                <xs:element name="teléfono" type="xs:string" minOccurs="0" />
                <xs:element name="enviar" type="xs:string" default="SI" />
                <xs:element name="dirección" type="xs:string" minOccurs="0" />
                <xs:element name="precio" type="xs:decimal" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EloRP/DAM1_LDM/UD4_A1/TAREFA4B/Pizza1.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizza xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pizza.xsd">
    <tamaño>grande</tamaño>
    <tipo>vegetariana</tipo>
    <extra_mozzarela>No</extra_mozzarela>
    <anchoas>Yes</anchoas>
    <atún>No</atún>
    <pimiento>Yes</pimiento>
    <jamón>No</jamón>
    <nombre>Carlos</nombre>
    <apellidos>García López</apellidos>
    <teléfono>123456789</teléfono>
    <enviar>SI</enviar>
    <dirección>Calle Ejemplo, 123</dirección>
    <precio>12.50</precio>
</pizza>

=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA4B/Pizza2.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizza xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Pizza.xsd">
    <tamaño>mediana</tamaño>
    <tipo>hawaiana</tipo>
    <nombre>Marta</nombre>
    <apellidos>Ruiz Pérez</apellidos>
    <teléfono>986892207</teléfono>
    <enviar>NO</enviar>
    <precio>9.99</precio>
</pizza>
