=== EloRP/DAM1_LDM/UD4_A1/TAREFA4/T4B/UD4_T4B_EloyRodalPerez.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT musica (cd|musico)*>
<!ELEMENT cd EMPTY>
<!ATTLIST cd
    titulo CDATA #IMPLIED
    ano CDATA #IMPLIED
    interprete CDATA #IMPLIED
>
<!ELEMENT musico (nomeArtistico|tipo|instrumento)*>
<!ATTLIST musico
    codigo CDATA #IMPLIED
>
<!ELEMENT nomeArtistico (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT instrumento (#PCDATA)>

=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA4/T4B/UD4_T4B_EloyRodalPerez.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE musica SYSTEM "UD4_T4B_EloyRodalPerez.dtd">
<musica>
    <cd titulo="Álbum1" ano="2022" interprete="artista1"/>
    <cd titulo="Álbum2" interprete="artista2"/>
    <musico codigo="m1">
        <nomeArtistico>Artista 1</nomeArtistico>
        <tipo>Cantante</tipo>
        <instrumento>Voz</instrumento>
    </musico>
    <musico codigo="m2">
        <nomeArtistico>Artista 2</nomeArtistico>
        <tipo>Instrumentista</tipo>
        <instrumento>Guitarra</instrumento>
    </musico>
    <musico codigo="m3">
        <nomeArtistico>Artista 3</nomeArtistico>
        <instrumento>Batería</instrumento>
    </musico>
</musica>
