=== EloRP/DAM1_LDM/UD4_A1/TAREFA5/UD4_T5B_EloyRodalPerez.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empregado" type="tipoEmpregado" maxOccurs="200"/>
                <xs:element name="departamento" type="tipoDepartamento" maxOccurs="8"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="depUnico">
            <xs:selector xpath="departamento"/>
            <xs:field xpath="@codigo"/>
        </xs:key>
        <xs:keyref name="departamento" refer="depUnico">
            <xs:selector xpath="empregado"/>
            <xs:field xpath="departamento"/>
        </xs:keyref>
        <xs:key name="xefeDepartamento">
            <xs:selector xpath="empregado"/>
            <xs:field xpath="nss" />
        </xs:key>
        <xs:keyref name="depXefe" refer="xefeDepartamento">
            <xs:select xpath="departamento"/>
            <xs:field xpath="@xefe" />
        </xs:keyref>
    </xs:element>
  
    <xs:complexType name="tipoEmpregado">
        <xs:sequence>
            <xs:element name="NSS" type="tipoNSS"/>
            <xs:element name="nome" type="xs:string"/>
            <xs:element name="departamento" type="xs:string"/>
            <xs:element name="contactos" type="telefonos" nillable="true" use="required"/>
        </xs:sequence>
    </xs:complexType>
  
    <xs:simpleType name="tipoNSS">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{12}"/>
        </xs:restriction>
    </xs:simpleType>
  
    <xs:complexType name="tipoDepartamento">
        <xs:sequence>
            <xs:element name="nome" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="tipoTelefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="telefonos">
        <xs:restriction base="ListaTelefonoss">
                    
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== EloRP/DAM1_LDM/UD4_A1/TAREFA5/UD4_T5B_EloyRodalPerez.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UD4_T5B_EloyRodalPerez.xsd">
  <empregado>
    <nome>Juan Pérez</nome>
    <departamento>Ventas</departamento>
    <NSS>123456789012</NSS>
    <contactos>987654321 123456789</contactos>
  </empregado>
  <empregado>
    <nome>Maria López</nome>
    <departamento>Recursos Humanos</departamento>
    <NSS>987654321098</NSS>
    <contactos>876543210 234567890</contactos>
  </empregado>
  <departamento codigo="001" xefe="2831239201389">
    <nome>Ventas</nome>
  </departamento>
  <departamento codigo="002" xefe="2843231239201389">
    <nome>Recursos Humanos</nome>
  </departamento>
</empresa>
