=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA3/UD4_T3a_EloyRodalPerez.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="garderia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="neno" minOccurs="1" maxOccurs="50"
                            type="tipoNeno"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
    <xs:sequence>
        <xs:simpleType name="tipoSexo">
            <xs:restriction base="xs:string">
                <xs:enumeration value="M"></xs:enumeration>
                <xs:enumeration value="H"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
            
        <xs:simpleType name="tipoPeso">
            <xs:restriction base="xs:decimal" fractionDigits = "1">
            </xs:restriction>
        </xs:simpleType>
            
        <xs:simpleType name="tipoNome">
            <xs:restriction base="xs:decimal" minLength="3" maxLength="80">
            </xs:restriction>
        </xs:simpleType>
              
        <xs:simpleType name="tipoCodigo">
            <xs:restriction base="xs:string">
                <xs:pattern value="[PM][3-7]{2}([-][0-9]{3})*?"/>
            </xs:restriction>
        </xs:simpleType>
            
        <xs:simpleType name="tipoTelefono">
            <xs:attribute name="relación"> 
                <xs:restriction base="xs:unsignedByte">
                    <xs:pattern value="([0-9]{9})"/>
                </xs:restriction>
            </xs:attribute>
        </xs:restriction>
        </xs:simpleType>
            
        <xs:complexType name="tipoNeno">
            <xs:element name="nome" type="xs:tipoNome"/>
            <xs:element name="dataNacemento" type="xs:date"/>
            <xs:element name="peso" type="xs:tipoPeso"/>
            <xs:element name="altura" type="xs:unsignedByte"/>
            <xs:element name="vacunas" type="xs:boolean"/>
            <xs:element name="sexo" type="xs:tipoSexo"/>
            <xs:element name="contacto" type="xs:tipoTelefono" maxOccur="4"/>
            <xs:element name="idade" type="tipoIdade"/>
            <xs:attribute />
        </xs:complexType>
        <xs:element name="contacto">
            <xs:complexType>
                <xs:attribute name="unidade" type="xsd:string"/>
                <xs:attribute name="valor" type="xsd:decimal"/>
            </xs:complexType>
        </xs:element>

        <xs:element name="idade" type="xs:tipoIdade"/>
    </xs:sequence>
    <xs:attribute name="numeroExpedente" type="xs:unsignedShort"/>
    <xs:attribute name="codigo" type="xs:tipoCodigo"/>

</xs:complexType>
</xs:schema>

=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA3/UD4_T3a_EloyRodalPerez.xml
<?xml version="1.0"?>
<garderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="UD4_T3a_EloyRodalPerez.xsd">
  <neno numeroExpedente="323">
    <nome>Pedro</nome>
    <dataNacemento>2019-12-6</dataNacemento>
    <peso>21</peso>
    <altura>50</altura>
    <vacuna>true</vacuna>
    <sexo>H</sexo>
    <contacto parentesco="nai">999999999</contacto>
    <contacto parentesco="pai">999999999</contacto>
  </neno>
</garderia>
