=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA4/T4C/UD4_T4C_EloyRodalPerez.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT panaderias (panaderia)*>
<!ELEMENT panaderia (idPanadería|domicilio|telefono|pedido)*>
<!ELEMENT idPanadería (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT pedido (fecha|ingrediente)*>
<!ATTLIST pedido
    numPedido CDATA #IMPLIED
    tipo CDATA #IMPLIED
  >
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT ingrediente (idIngrediente|ano|origen)*>
<!ELEMENT idIngrediente (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT origen EMPTY>
<!ATTLIST origen
    continente CDATA #IMPLIED
  >

=== EloRP/DAM1_LDM/UD4/UD4_A1/TAREFA4/T4C/UD4_T4C2_EloyRodalPerez.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE panaderias SYSTEM "UD4_T4C_EloyRodalPerez.dtd">
<panaderias>
    <panaderia>
        <idPanadería>2</idPanadería>
        <telefono>986892207</telefono>
        <pedido numPedido="p2">
            <fecha>2024-03-07</fecha>
            <ingrediente>
                <idIngrediente>3</idIngrediente>
                <ano>2023</ano>
                <origen continente="America"/>
            </ingrediente>
            <ingrediente>
                <idIngrediente>4</idIngrediente>
                <ano>2024</ano>
                <origen continente="Africa"/>
            </ingrediente>
        </pedido>
    </panaderia>
    <panaderia>
        <idPanadería>3</idPanadería>
        <telefono>645423521</telefono>
        <pedido numPedido="p3" tipo="urgente">
            <fecha>2024-03-08</fecha>
            <ingrediente>
                <idIngrediente>5</idIngrediente>
                <ano>2024</ano>
                <origen continente="Europa"/>
            </ingrediente>
            <ingrediente>
                <idIngrediente>6</idIngrediente>
                <ano>2023</ano>
            </ingrediente>
        </pedido>
    </panaderia>
</panaderias>
